#!/bin/bash

# requires: autoconf, libtool, libreadline-dev

mkdir ext
cd ext

#zookeeper
if [ 1 == 2 ]
then
wget http://apache.org/dist/zookeeper/zookeeper-3.4.10/zookeeper-3.4.10.tar.gz
tar xzf zookeeper-3.4.10.tar.gz
rm zookeeper-3.4.10.tar.gz
mv zookeeper-3.4.10/src/c zookeeper
rm -fr zookeeper-3.4.10
cd zookeeper
./configure --prefix=$PWD
make -j6
cd ..

# protobuf
git clone https://github.com/google/protobuf.git
cd protobuf
./autogen.sh
./configure --prefix=$PWD
make -j6
cd ..

# googletest
wget https://src.fedoraproject.org/repo/pkgs/gtest/gtest-1.6.0.zip/md5/4577b49f2973c90bf9ba69aa8166b786/gtest-1.6.0.zip 
unzip gtest-1.6.0.zip
rm gtest-1.6.0.zip
mv gtest-1.6.0 googletest
cd googletest
./configure --prefix=$PWD
make -j6
cd ..
fi


# zeromq
wget https://archive.org/download/zeromq_2.1.11/zeromq-2.1.11.tar.gz 
tar xzf zeromq-2.1.11.tar.gz
rm zeromq-2.1.11.tar.gz
mv zeromq-2.1.11 zeromq
cd zeromq
./autogen.sh
./configure --prefix=$PWD
make -j6
make install
cd ..



